## Load data

Loading data from the Benign/Dictionary Brute Force/DNS_Spoofing dataset. Since the CIC IoT Intrusion dataset for benign traffic comes with a number of batches of data, which we are using to train our autoencoder, we can simply designate one of them for training and the other for testing instead of spliting up a single dataset. This is done under the assumption that these benign traffic datasets are independent from each other; training the autoencoder with one of them should not "leak" any information about the test benign traffic dataset.

In [14]:
import pandas as pd
from IPython.display import display

# Read BenignTraffic for training
benign_train = pd.read_csv("./BenignTraffic.pcap.csv")
display(benign_train.head())

# Read BenignTraffic for testing
benign_test = pd.read_csv("./BenignTraffic1.pcap.csv")
display(benign_test.head())

# Read Dictionary Brute Force
brute = pd.read_csv("./DictionaryBruteForce.pcap.csv")
display(brute.head())

# Reda DNS_Spoofing
spoof = pd.read_csv("./DNS_Spoofing.pcap.csv")
display(spoof.head())

,Header_Length,Protocol Type,Time_To_Live,Rate,fin_flag_number,syn_flag_number,rst_flag_number,psh_flag_number,ack_flag_number,ece_flag_number,...,LLC,Tot sum,Min,Max,AVG,Std,Tot size,IAT,Number,Variance
0,32.0,6,198.4,430.273287,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,5004,66,2962,500.4,977.325512,500.4,0.002324,10,9.551652e+05
1,22.4,6,114.4,484.616113,0.0,0.0,0.0,0.2,0.6,0.0,...,1.0,1404,60,583,140.4,174.827026,140.4,0.002179,10,3.056449e+04
2,27.2,6,62.5,398.610950,0.0,0.0,0.0,0.0,0.8,0.0,...,1.0,10784,60,1514,1078.4,701.384536,1078.4,0.003173,10,4.919403e+05
3,23.2,6,62.1,425.187438,0.0,0.1,0.0,0.0,0.6,0.0,...,1.0,7884,60,2962,788.4,1025.156812,788.4,0.002507,10,1.050946e+06
4,32.0,6,64.0,1563.521956,0.0,0.0,0.0,0.1,1.0,0.0,...,1.0,13782,156,1514,1378.2,429.437306,1378.2,0.000660,10,1.844164e+05

,Header_Length,Protocol Type,Time_To_Live,Rate,fin_flag_number,syn_flag_number,rst_flag_number,psh_flag_number,ack_flag_number,ece_flag_number,...,LLC,Tot sum,Min,Max,AVG,Std,Tot size,IAT,Number,Variance
0,25.6,6,67.2,111.733096,0.0,0.1,0.0,0.1,0.6,0.0,...,1.0,8010,60,2962,801.0,1015.627338,801.0,0.008950,10,1.031499e+06
1,32.0,6,64.0,905.799374,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,20932,1514,4410,2093.2,1221.060814,2093.2,0.001122,10,1.490990e+06
2,32.0,6,80.8,931.177763,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,25276,66,5858,2527.6,1936.690602,2527.6,0.001091,10,3.750770e+06
3,32.0,6,232.0,1419.440252,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,660,66,66,66.0,0.000000,66.0,0.000814,10,0.000000e+00
4,32.0,6,181.2,211.585617,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,3556,66,1514,355.6,610.530407,355.6,0.004726,10,3.727474e+05

,Header_Length,Protocol Type,Time_To_Live,Rate,fin_flag_number,syn_flag_number,rst_flag_number,psh_flag_number,ack_flag_number,ece_flag_number,...,LLC,Tot sum,Min,Max,AVG,Std,Tot size,IAT,Number,Variance
0,27.2,6,117.3,30.188314,0.2,0.0,0.0,0.3,1.0,0.0,...,1.0,856,60,150,85.6,38.178528,85.6,0.033125,10,1.457600e+03
1,30.0,6,98.3,30.214476,0.0,0.2,0.1,0.3,0.9,0.0,...,1.0,846,60,150,84.6,32.042333,84.6,0.034126,10,1.026711e+03
2,19.6,6,85.1,121.404766,0.0,0.0,0.0,0.5,0.7,0.0,...,0.8,1004,60,214,100.4,55.887188,100.4,0.018915,10,3.123378e+03
3,26.0,6,117.6,31.979237,0.0,0.3,0.0,0.1,0.5,0.0,...,1.0,1146,60,309,114.6,84.602600,114.6,0.031634,10,7.157600e+03
4,16.8,17,130.0,108.038246,0.0,0.0,0.0,0.2,0.4,0.0,...,0.9,4542,60,3534,454.2,1084.478963,454.2,0.010831,10,1.176095e+06

,Header_Length,Protocol Type,Time_To_Live,Rate,fin_flag_number,syn_flag_number,rst_flag_number,psh_flag_number,ack_flag_number,ece_flag_number,...,LLC,Tot sum,Min,Max,AVG,Std,Tot size,IAT,Number,Variance
0,10.4,17,63.6,6427.067116,0.0,0.0,0.0,0.1,0.1,0.0,...,1.0,6391,140,1074,639.1,296.700541,639.1,0.000156,10,88031.211111
1,8.0,17,64.0,2434.868222,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,6989,46,1074,698.9,343.381696,698.9,0.000655,10,117910.988889
2,9.2,17,59.8,1138.951828,0.0,0.0,0.0,0.1,0.1,0.0,...,1.0,4387,46,1074,438.7,483.072585,438.7,0.000955,10,233359.122222
3,8.0,17,50.0,4520.698426,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,7859,362,1074,785.9,259.964292,785.9,0.000221,10,67581.433333
4,8.0,17,51.4,1231.988251,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,6164,356,796,616.4,217.480625,616.4,0.000851,10,47297.822222

Show statistics (such as mean, median, standard deviation etc.) of each column:

In [5]:
# Show statistics of the dataset
display(benign_train.describe())
display(benign_test.describe())

,Header_Length,Protocol Type,Time_To_Live,Rate,fin_flag_number,syn_flag_number,rst_flag_number,psh_flag_number,ack_flag_number,ece_flag_number,...,LLC,Tot sum,Min,Max,AVG,Std,Tot size,IAT,Number,Variance
count,362361.000000,362361.000000,362361.000000,3.623610e+05,362361.000000,362361.000000,362361.000000,362361.000000,362361.000000,362361.000000,...,362361.000000,362361.000000,362361.000000,362361.000000,362361.000000,362342.000000,362361.000000,3.623610e+05,362361.000000,3.623420e+05
mean,26.701672,7.107147,108.504222,inf,0.022801,0.025565,0.001970,0.173028,0.769602,0.000337,...,0.975568,5475.835093,118.129713,1518.459876,547.956289,496.175465,547.956289,9.198666e-03,9.997696,6.483441e+05
std,6.983413,3.343224,48.370953,NaN,0.050855,0.052081,0.019888,0.156156,0.249253,0.006160,...,0.059382,6380.254167,271.149036,1955.290549,638.860704,634.157032,638.860704,9.299444e-03,0.118089,1.995883e+06
min,0.000000,0.000000,0.000000,7.697838e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,60.000000,60.000000,60.000000,60.000000,0.000000,60.000000,6.357829e-07,1.000000,0.000000e+00
25%,22.400000,6.000000,70.000000,8.522029e+01,0.000000,0.000000,0.000000,0.100000,0.600000,0.000000,...,1.000000,994.000000,60.000000,230.000000,99.400000,56.577282,99.400000,2.156687e-03,10.000000,3.200989e+03
50%,28.000000,6.000000,93.500000,1.610023e+02,0.000000,0.000000,0.000000,0.100000,0.888889,0.000000,...,1.000000,1728.000000,66.000000,573.000000,172.800000,154.712960,172.800000,7.059383e-03,10.000000,2.393610e+04
75%,32.000000,6.000000,131.400000,5.577235e+02,0.000000,0.000000,0.000000,0.300000,1.000000,0.000000,...,1.000000,9188.000000,66.000000,2858.000000,918.800000,762.428000,918.800000,1.279159e-02,10.000000,5.812965e+05
max,60.000000,17.000000,250.600000,inf,0.900000,1.000000,1.000000,1.000000,1.000000,0.400000,...,1.000000,94303.000000,13583.000000,37714.000000,13583.000000,11655.404669,13583.000000,1.388082e-01,10.000000,1.358485e+08

,Header_Length,Protocol Type,Time_To_Live,Rate,fin_flag_number,syn_flag_number,rst_flag_number,psh_flag_number,ack_flag_number,ece_flag_number,...,LLC,Tot sum,Min,Max,AVG,Std,Tot size,IAT,Number,Variance
count,295585.000000,295585.000000,295585.000000,2.955850e+05,295585.000000,295585.000000,295585.000000,295585.000000,295585.000000,295585.000000,...,295585.000000,295585.000000,295585.000000,295585.000000,295585.000000,295565.000000,295585.000000,2.955850e+05,295585.000000,2.955650e+05
mean,28.084172,6.697502,117.362243,inf,0.004887,0.007746,0.001894,0.159926,0.832727,0.000420,...,0.976524,6751.723183,137.017464,1895.623144,675.757354,617.829740,675.757354,8.828839e-03,9.996749,8.693773e+05
std,6.425547,2.725548,51.282213,NaN,0.024535,0.031019,0.020004,0.153288,0.215690,0.007092,...,0.061041,6873.524746,314.748209,2185.028484,688.521578,698.330413,688.521578,9.551404e-03,0.144078,2.317304e+06
min,0.000000,0.000000,0.000000,7.487495e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,60.000000,60.000000,60.000000,60.000000,0.000000,60.000000,8.106232e-07,1.000000,0.000000e+00
25%,24.800000,6.000000,76.700000,8.832438e+01,0.000000,0.000000,0.000000,0.000000,0.700000,0.000000,...,1.000000,1040.000000,60.000000,230.000000,104.000000,57.533469,104.000000,1.595306e-03,10.000000,3.310100e+03
50%,29.600000,6.000000,99.800000,1.903456e+02,0.000000,0.000000,0.000000,0.100000,0.900000,0.000000,...,1.000000,3875.000000,66.000000,1514.000000,387.900000,495.035004,387.900000,6.026196e-03,10.000000,2.450597e+05
75%,32.000000,6.000000,149.500000,7.681031e+02,0.000000,0.000000,0.000000,0.200000,1.000000,0.000000,...,1.000000,11008.000000,66.000000,2962.000000,1102.000000,962.763522,1102.000000,1.241870e-02,10.000000,9.269136e+05
max,60.000000,17.000000,255.000000,inf,0.400000,0.900000,1.000000,1.000000,1.000000,0.300000,...,1.000000,71856.000000,10202.000000,33370.000000,10202.000000,10337.452762,10202.000000,1.384385e-01,10.000000,1.068629e+08

Because we see that `Rate` column has unprocessable values, we will remove that feature for preprocessing step later.

In [15]:
# Delete problematic feature from datasets
del benign_train["Rate"]
del benign_test["Rate"]
del brute["Rate"]
del spoof["Rate"]

## Preprocessing - MinMax scaling of features

This is the feature scaling step for the datasets. We will use the `MinMaxScaler()` to scale the features.

In [16]:
from sklearn.preprocessing import MinMaxScaler

# Instantiate the MinMaxScaler() for create a common scaler for datasets
scaler = MinMaxScaler()

# Create copies of the dataframe before modifying them
benign_test_copy = benign_test.copy()
benign_train_copy = benign_train.copy()
brute_copy = brute.copy()
spoof_copy = spoof.copy()

# Features obtained from `MinMaxScaler`
benign_train_minmax = scaler.fit_transform(benign_train_copy)
benign_test_minmax = scaler.transform(benign_test_copy)
brute_minmax = scaler.transform(brute_copy)
spoof_minmax = scaler.transform(spoof_copy)

# Print the shape of the output to check
print(benign_train_minmax.shape)
print(benign_test_minmax.shape)
print(brute_minmax.shape)
print(spoof_minmax.shape)

(362361, 38)
(295585, 38)
(13064, 38)
(178898, 38)

## Autoencoder Design

Now that data features are scaled properly, we define the structure of the autoencoder that will be used to classify the IoT attacks.

We will also use the following `timeit` function to monitor the training time of each algorithm:

In [11]:
import time
from contextlib import contextmanager

@contextmanager
def timeit(action="Timing"):
    # Record start time
    print(f"{action} started...")
    start_time = time.time()

    # Execute task
    yield

    # Compute and show elapsed time
    elapsed_time = time.time()-start_time
    print(f"{action} completed. Elapsed time: {elapsed_time:.2f}s")

# Test timing function by sleeping for 1 second
with timeit("Testing timing function"):
    time.sleep(1)

Testing timing function started...
Testing timing function completed. Elapsed time: 1.00s

## Autoencoder

We will wrap up the introduction of dimensionality reduction algorithms with autoencoders. An **autoencoder** is a neural network used to learn a compact representation (also called encoding) for a set of data, typically for the purpose of dimensionality reduction. A typical regular autoencoder has a symmetric, five-layer structure shown below:

![autoencoder-structure.png](attachment:autoencoder-structure.png)

Like all other neural networks, the first layer is the **input layer** and the **last layer** is the output layer. For an autoencoder, the input layer and the output layer always have the same shape. We call the first three layers of the autoencoder **encoder network** and the last three layers **decoder network**. Hence, the second layer can be seen as the hidden layer of the encoder network and the fourth layer can be seen as the hidden layer of the decoder network. In practice, the shape of these layers are also made same. The third layer is the **encoder output layer**, and we make it the "bottleneck" of the autoencoder (by reducing its dimensions) so that the neural network learns to "compress" the information of previous encoder layers.

The goal of the autoencoder is to learn to **compress and reconstruct input features**, such that the **reconstruction resembles the original input** as much as possible. This forces the autoencoder to focus on the useful properties of the features and discard the noises. After training, we throw away the decoder network and use the encoder network to transform features. The result of the transformation will have fewer dimensions, yet it still preserves the characteristics and properties of the original, high-dimensional inputs.

From a formal perspective, we define the encoder transformation as $\phi: \mathcal{X} \rightarrow \mathcal{F}$ and the decoder transformation as $\psi: \mathcal{F} \rightarrow \mathcal{X}$, where $\mathcal{X}$ is the original feature space and $\mathcal{F}$ is the target feature space. Then the goal of the autoencoder is to minimize the mean-squared loss between the inputs and reconstructions:

$$
l_{AE} = ||X - \psi(\phi(X))||_2^2
$$

After training, we compute $F = \phi(X)$ to obtain target features with reduced dimensions.

Now, let's build an autoencoder in the following `make_ae_models` function. We have given you the dimensions of input features, hidden layers and the encoder output ("bottleneck") layer, as well as the activation layer type. Your task is to create an encoder and a decoder model, **both with three layers (this is different from the figure above!)**, according to the instructions in comments below. The `autoencoder_loss` function handles computation of the autoencoder (mean-squared) loss.

In [17]:
import torch
from torch import nn
from torch.nn import functional as f
from torch.utils.data import DataLoader

def get_torch_device():
    # Use CUDA (Nvidia/AMD GPU) if available
    if torch.cuda.is_available():
        device = "cuda"
    # Use MPS (Apple Silicon GPU) if available
    elif torch.backends.mps.is_available():
        device = "mps"
    # Fallback to CPU
    else:
        device = "cpu"

    return torch.device(device)


def make_ae_models(
    feat_dims, hidden_dims, bottleneck_dims,
    activation=nn.GELU, dropout_ratio=0., device="cpu"
):
    """Create and return both encoder and decoder PyTorch models."""

    # Define encoder model
    encoder_model = nn.Sequential(
        # Implement the encoder model to match the reference solution structure:
        #
        #   (*, feat_dims)
        #     -> Linear(feat_dims, hidden_dims)
        #     -> activation()
        #     -> Dropout(dropout_ratio)
        #     -> Linear(hidden_dims, bottleneck_dims)
        #
        # Add the 4 modules below in the correct order:
        torch.nn.Linear(feat_dims, hidden_dims),  # first Linear
        activation(),  # activation
        torch.nn.Dropout(dropout_ratio),  # dropout
        torch.nn.Linear(hidden_dims, bottleneck_dims),  # bottleneck Linear
    )

    # Define decoder model
    decoder_model = nn.Sequential(
        # Implement the decoder model to match the reference solution structure:
        #
        #   (*, bottleneck_dims)
        #     -> Linear(bottleneck_dims, hidden_dims)
        #     -> Dropout(dropout_ratio)
        #     -> activation()
        #     -> Linear(hidden_dims, feat_dims)
        #
        # Add the 4 modules below in the correct order:
        torch.nn.Linear(bottleneck_dims, hidden_dims),  # first Linear
        torch.nn.Dropout(dropout_ratio),  # dropout
        activation(),  # activation
        torch.nn.Linear(hidden_dims, feat_dims),  # output Linear
    )

    # Move models to given PyTorch device
    encoder_model = encoder_model.to(device)
    decoder_model = decoder_model.to(device)

    return encoder_model, decoder_model


def autoencoder_loss(feats, reconstructs, bottlenecks=None, l2_reg_factor=None):
    # Compute mean square error (main) loss between original and reconstructed features
    mse_loss = f.mse_loss(feats, reconstructs)

    # L2 regularization loss for bottleneck features
    if l2_reg_factor:
        l2_reg_loss = bottlenecks.square().sum(-1).mean()
        total_loss = mse_loss+l2_reg_factor*l2_reg_loss
    else:
        total_loss = mse_loss

    return total_loss, mse_loss